package com.cmedhealth.flutter.bmi.cmed_bmi_devices_lib.aifit

enum class ResponseEnum {
    //AiFit FatScale
    CS_WEIGHT_BLE_DISABLED,
    CS_WEIGHT_ACTION_SEARCHING,
    CS_WEIGHT_ACTION_DEVICE_FOUND,
    CS_WEIGHT_ACTION_DEVICE_NOT_FOUND,
    CS_WEIGHT_ACTION_CONNECTING,
    CS_WEIGHT_ACTION_CONNECTED,
    CS_WEIGHT_ACTION_DISCONNECTED,
    CS_WEIGHT_ERROR,
    CS_ONLINE_WEIGHT,
    CS_FAT_DATA,
    CS_ANALYZING,
    CS_SCREEN_OFF,
    CS_LOW_VOLTAGE,
    CS_WEIGHING_OVERLOAD,
    CS_WEIGHING_TIMEOUT,
    CS_IMPEDANCE_MEASUREMENT_FAILED,
    CS_PERMISSION_DENIED,
}